language: generic
os:
  - linux
matrix:
  include:
    - dist: xenial
services:
  - docker

before_install:
  - docker build -t friendou/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true friendou/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name;
